package com.ledgermatch.explanations;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ledgermatch.security.CurrentUser;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@RestController
public class ExplanationController {
    private final JdbcTemplate db; private final ObjectMapper json; private final RestClient client; private final String apiKey;
    public ExplanationController(JdbcTemplate db,ObjectMapper json,@Value("${app.openai-api-key:}")String apiKey){this.db=db;this.json=json;this.apiKey=apiKey;this.client=RestClient.builder().baseUrl("https://api.openai.com/v1").build();}
    @PostMapping("/discrepancies/{id}/explain") public Map<String,Object> explain(@PathVariable UUID id){UUID user=CurrentUser.id(); List<Map<String,Object>> cached=db.query("select model,temperature,likely_cause,recommended_action,confidence from discrepancy_explanations e join discrepancies d on d.id=e.discrepancy_id where e.discrepancy_id=? and d.user_id=?",(rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("model",rs.getString("model"));row.put("temperature",rs.getBigDecimal("temperature"));row.put("likelyCause",rs.getString("likely_cause"));row.put("recommendedAction",rs.getString("recommended_action"));row.put("confidence",rs.getString("confidence"));return row;},id,user); if(!cached.isEmpty())return cached.getFirst();
        var rows=db.query("select d.type,d.severity,d.amount_at_risk,d.details,o.order_id,o.customer_email from discrepancies d left join orders o on o.id=d.order_id and o.user_id=d.user_id where d.id=? and d.user_id=?",(rs,n)->{Map<String,Object> fact=new LinkedHashMap<>();fact.put("type",rs.getString("type"));fact.put("severity",rs.getString("severity"));fact.put("amount",rs.getBigDecimal("amount_at_risk"));fact.put("details",rs.getString("details"));fact.put("orderId",rs.getString("order_id"));fact.put("customerEmail",rs.getString("customer_email"));return fact;},id,user); if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND); if(apiKey.isBlank())return fallback(rows.getFirst());
        String prompt="Explain this deterministic reconciliation discrepancy. Return only JSON with likely_cause, recommended_action, confidence. Facts: "+rows.getFirst(); JsonNode answer=null; for(int attempt=0;attempt<2&&answer==null;attempt++){try{String body=json.writeValueAsString(Map.of("model","gpt-4o-mini","temperature",0.2,"messages",List.of(Map.of("role","system","content","You explain accounting exceptions concisely."),Map.of("role","user","content",prompt)),"response_format",Map.of("type","json_object")));String raw=client.post().uri("/chat/completions").header("Authorization","Bearer "+apiKey).header("Content-Type","application/json").body(body).retrieve().body(String.class);JsonNode root=json.readTree(raw);String content=root.path("choices").path(0).path("message").path("content").asText();JsonNode parsed=json.readTree(content);if(parsed.has("likely_cause")&&parsed.get("likely_cause").isTextual()&&parsed.has("recommended_action")&&parsed.get("recommended_action").isTextual()&&parsed.has("confidence")&&parsed.get("confidence").isTextual())answer=parsed;}catch(Exception ignored){}}
        if(answer==null)return fallback(rows.getFirst()); try{Map<String,Object> out=Map.of("available",true,"model","gpt-4o-mini","temperature",0.2,"likelyCause",answer.get("likely_cause").asText(),"recommendedAction",answer.get("recommended_action").asText(),"confidence",answer.get("confidence").asText());db.update("insert into discrepancy_explanations(discrepancy_id,model,temperature,likely_cause,recommended_action,confidence,raw_response) values (?,?,?,?,?,?,?::jsonb)",id,"gpt-4o-mini",0.2,answer.get("likely_cause").asText(),answer.get("recommended_action").asText(),answer.get("confidence").asText(),answer.toString());return out;}catch(Exception e){return fallback(rows.getFirst());}
    }
    private Map<String,Object> fallback(Map<String,Object> fact){String type=String.valueOf(fact.get("type"));String cause;String action;switch(type){case "MISSING_PAYMENT"-> {cause="The order exists in the store export, but no payment record matched its normalized order id.";action="Check the payment processor for a failed or omitted charge, then confirm whether the customer should be contacted or the order cancelled.";}case "ORPHAN_PAYMENT"-> {cause="A payment references an order id that is absent from the uploaded orders export.";action="Search the store system for the referenced order and verify whether the order export was incomplete or the payment was attached to the wrong order.";}case "AMOUNT_MISMATCH"-> {cause="The order net amount and settled charge differ beyond the $0.02 tolerance.";action="Compare the original checkout total, discounts, and processor charge, then recover an undercharge or refund an overcharge.";}case "DUPLICATE_CHARGE"-> {cause="More than one settled charge was found for the same order.";action="Review the transaction references and refund the duplicate customer charge after confirming settlement.";}case "CANCELLED_BUT_CHARGED"-> {cause="The order is cancelled but a settled charge remains.";action="Verify fulfilment did not occur and issue a customer refund if the charge is not valid.";}case "STATUS_CONFLICT"-> {cause="The order is marked completed but its payment is pending or failed.";action="Confirm settlement with the processor before fulfilment and update the order or retry payment as appropriate.";}case "PARTIAL_REFUND"-> {cause="The order is marked refunded, but the refund total is smaller than the charge total.";action="Compare refund transactions with the original charge and issue the remaining refund if required.";}case "STALE_STATUS"-> {cause="Payment records show a full refund while the order status is not refunded.";action="Update the order status and confirm downstream revenue reporting reflects the refund.";}case "CURRENCY_MISMATCH"-> {cause="The order and payment use different currency codes, so the values cannot be safely compared.";action="Verify the original transaction currency and correct the source metadata before making a financial adjustment.";}default->{cause="The reconciliation engine found an inconsistency between the order and payment records.";action="Review the linked source records and resolve the underlying data or settlement issue.";}}return Map.of("available",true,"model","deterministic-fallback","temperature",0,"likelyCause",cause,"recommendedAction",action,"confidence","rule-based");}
}