import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { createColumnHelper, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import './styles.css'

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'
type Row = { id: string; type: string; severity: string; amountAtRisk: number; orderId?: string; customerEmail?: string }
type Summary = { totalOrders: number; totalPayments: number; valueReconciled: number; valueInDispute: number; moneyAtRisk: number; breakdown: { type: string; severity: string; count: number }[] }
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value)
async function request(path: string, init: RequestInit = {}) { const headers = new Headers(init.headers); const token = localStorage.getItem('token'); if (token) headers.set('Authorization', `Bearer ${token}`); const response = await fetch(API + path, { ...init, headers }); if (response.status === 401 || response.status === 403) { localStorage.removeItem('token'); throw new Error('Your session expired. Please log in again.') } if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message ?? 'Request failed'); return response.json() }

function Auth({ onLogin }: { onLogin: () => void }) { const [mode, setMode] = useState<'login'|'signup'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const data = await request(`/auth/${mode}`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ email, password }) }); localStorage.setItem('token', data.token); onLogin() } catch (error) { setError(error instanceof Error ? error.message : 'Unable to sign in') } finally { setBusy(false) } }
  return <main className="auth"><section><p className="eyebrow">Ledger Match</p><h1>Find the leak in the ledger.</h1><p className="lede">A clear view of what was sold, charged, settled, and left unresolved.</p></section><form onSubmit={submit} className="panel"><div className="tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Log in</button><button type="button" className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Create account</button></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Working...':mode==='login'?'Enter dashboard':'Create account'}</button></form></main> }

function Upload({ onRun }: { onRun: (id:string, summary:Summary)=>void }) { const [orders,setOrders]=useState<File>(); const [payments,setPayments]=useState<File>(); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  async function run(){if(!orders||!payments)return;setBusy(true);setError('');try{for(const [path,file] of [['orders',orders],['payments',payments]] as const){const form=new FormData();form.append('file',file);await request(`/datasets/${path}`,{method:'POST',body:form})}const result=await request('/reconciliation/runs',{method:'POST'});const summary=await request(`/reconciliation/runs/${result.runId}/summary`);onRun(result.runId,summary)}catch(error){setError(error instanceof Error?error.message:'Upload failed')}finally{setBusy(false)}}
  return <section className="upload panel"><p className="eyebrow">New reconciliation</p><h2>Bring both sides together.</h2><p className="muted">Files are normalized and stored under your account. Exact duplicates become ingestion warnings.</p><div className="file-grid"><label className="drop">Orders export<input type="file" accept=".csv" onChange={e=>setOrders(e.target.files?.[0])}/><strong>{orders?.name??'Choose orders.csv'}</strong></label><label className="drop">Payments export<input type="file" accept=".csv" onChange={e=>setPayments(e.target.files?.[0])}/><strong>{payments?.name??'Choose payments.csv'}</strong></label></div>{error&&<p className="error">{error}</p>}<button className="primary" disabled={!orders||!payments||busy} onClick={run}>{busy?'Reconciling...':'Run reconciliation'}</button></section> }

function Dashboard({ runId, summary, onReset }: { runId:string; summary:Summary; onReset:()=>void }) { const [rows,setRows]=useState<Row[]>([]); const [type,setType]=useState(''); const [severity,setSeverity]=useState(''); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [explaining,setExplaining]=useState<string>(); const [explanations,setExplanations]=useState<Record<string,any>>({})
  useEffect(()=>{setLoading(true);request(`/reconciliation/runs/${runId}/discrepancies?size=100&type=${type}&severity=${severity}&search=${encodeURIComponent(search)}`).then(data=>setRows(data.content)).catch(()=>setRows([])).finally(()=>setLoading(false))},[runId,type,severity,search])
  async function explain(id:string){setExplaining(id);try{const result=await request(`/discrepancies/${id}/explain`,{method:'POST'});setExplanations(old=>({...old,[id]:result}))}catch{setExplanations(old=>({...old,[id]:{available:false,message:'explanation unavailable - the numbers above are unaffected'}}))}finally{setExplaining(undefined)}}
  const helper=createColumnHelper<Row>(); const columns=[helper.accessor('type',{header:'Issue'}),helper.accessor('severity',{header:'Severity',cell:info=><span className={`pill ${info.getValue()}`}>{info.getValue()}</span>}),helper.accessor('orderId',{header:'Order'}),helper.accessor('amountAtRisk',{header:'At risk',cell:info=>money(info.getValue())}),helper.display({id:'action',header:'',cell:info=><button className="link" onClick={()=>explain(info.row.original.id)} disabled={explaining===info.row.original.id}>{explaining===info.row.original.id?'Thinking...':'Explain'}</button>})]; const table=useReactTable({data:rows,columns,getCoreRowModel:getCoreRowModel()})
  return <main className="dashboard"><header className="topbar"><div><p className="eyebrow">Ledger Match</p><h1>Reconciliation report</h1></div><button className="ghost" onClick={onReset}>New run</button></header><div className="kpis">{[['Orders',summary.totalOrders],['Payments',summary.totalPayments],['Reconciled',money(summary.valueReconciled)],['In dispute',money(summary.valueInDispute)],['Money at risk',money(summary.moneyAtRisk)]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="chart panel"><p className="eyebrow">Pressure points</p><h2>Discrepancies by type</h2><ResponsiveContainer width="100%" height={270}><BarChart data={summary.breakdown}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="type" tick={{fontSize:10}} interval={0} angle={-28} textAnchor="end" height={75}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#a34f31" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></section><section className="panel"><div className="table-head"><div><p className="eyebrow">Investigation queue</p><h2>Open discrepancies</h2></div><input placeholder="Search order or email" value={search} onChange={e=>setSearch(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{summary.breakdown.map(item=><option key={item.type}>{item.type}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option><option>critical</option><option>high</option></select></div>{loading?<p className="muted">Loading discrepancies...</p>:<div className="table-wrap"><table><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id}>{flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><><tr key={row.id}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>{explanations[row.original.id]&&<tr className="explanation"><td colSpan={5}>{explanations[row.original.id].available===false?explanations[row.original.id].message:<><strong>{explanations[row.original.id].likelyCause}</strong><br/>{explanations[row.original.id].recommendedAction} <small>Confidence: {explanations[row.original.id].confidence}</small></>}</td></tr>}</>)}</tbody></table></div>}</section></main> }

function App(){const [run,setRun]=useState<{id:string;summary:Summary}>();const [authed,setAuthed]=useState(!!localStorage.getItem('token'));if(!authed)return <Auth onLogin={()=>setAuthed(true)}/>;if(!run)return <><header className="topbar"><div><p className="eyebrow">Ledger Match</p><h1>Revenue control room</h1></div><button className="ghost" onClick={()=>{localStorage.removeItem('token');setAuthed(false)}}>Sign out</button></header><Upload onRun={(id,summary)=>setRun({id,summary})}/></>;return <Dashboard runId={run.id} summary={run.summary} onReset={()=>setRun(undefined)}/>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)